# Generated by Django 4.1.6 on 2023-02-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('duty_time', models.CharField(max_length=150)),
                ('OPD_time', models.CharField(max_length=150)),
                ('room_number', models.CharField(max_length=150)),
                ('hospital', models.ManyToManyField(to='hospitals.hospital')),
            ],
        ),
    ]
